git-svn-id: http://dcmd.googlecode.com/svn/trunk@34 139e6f35-fde5-aae7-7073-d4f4ae540fe1

diff --git a/src/agent/configure b/src/agent/configure
--- a/src/agent/configure
+++ b/src/agent/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL cwinux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL cwinux_dir protobuf_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1041,8 +1041,7 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-cwinux=DIR        cwinux directory
-  --with-zk=DIR        zookeeper c lib directory
-  --with-openssl=DIR        openssl lib directory
+  --with-protobuf=DIR     protobuf directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -1804,7 +1803,7 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE=unistore
+ PACKAGE=dcmd_agent
  VERSION=1.0
 
 
@@ -3691,7 +3690,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3694 "configure"' > conftest.$ac_ext
+  echo '#line 3693 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5290,7 +5289,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5293:" \
+echo "$as_me:5292:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6353,11 +6352,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6356: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6355: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6360: \$? = $ac_status" >&5
+   echo "$as_me:6359: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6621,11 +6620,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6624: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6623: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6628: \$? = $ac_status" >&5
+   echo "$as_me:6627: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6725,11 +6724,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6728: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6727: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6732: \$? = $ac_status" >&5
+   echo "$as_me:6731: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8194,7 +8193,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8197 "configure"' > conftest.$ac_ext
+    echo '#line 8196 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9091,7 +9090,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9094 "configure"
+#line 9093 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9191,7 +9190,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9194 "configure"
+#line 9193 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11534,11 +11533,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11537: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11536: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11541: \$? = $ac_status" >&5
+   echo "$as_me:11540: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11638,11 +11637,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11641: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11640: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11645: \$? = $ac_status" >&5
+   echo "$as_me:11644: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12174,7 +12173,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 12177 "configure"' > conftest.$ac_ext
+    echo '#line 12176 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13232,11 +13231,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13235: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13234: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13239: \$? = $ac_status" >&5
+   echo "$as_me:13238: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13336,11 +13335,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13339: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13338: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13343: \$? = $ac_status" >&5
+   echo "$as_me:13342: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14785,7 +14784,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14788 "configure"' > conftest.$ac_ext
+    echo '#line 14787 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15563,11 +15562,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15566: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15565: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15570: \$? = $ac_status" >&5
+   echo "$as_me:15569: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15831,11 +15830,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15834: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15833: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15838: \$? = $ac_status" >&5
+   echo "$as_me:15837: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15935,11 +15934,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15938: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15937: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15942: \$? = $ac_status" >&5
+   echo "$as_me:15941: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17404,7 +17403,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17407 "configure"' > conftest.$ac_ext
+    echo '#line 17406 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18914,35 +18913,22 @@ else
   with_cwinux="no"
 
 fi;
-    echo "$as_me:$LINENO: checking for libevent directory" >&5
-echo $ECHO_N "checking for libevent directory... $ECHO_C" >&6
 
-
-# Check whether --with-zk or --without-zk was given.
-if test "${with_zk+set}" = set; then
-  withval="$with_zk"
+# Check whether --with-protobuf or --without-protobuf was given.
+if test "${with_protobuf+set}" = set; then
+  withval="$with_protobuf"
 
 else
-  with_zk="no"
+  with_protobuf="no"
 
 fi;
-
-# Check whether --with-openssl or --without-openssl was given.
-if test "${with_openssl+set}" = set; then
-  withval="$with_openssl"
-
-else
-  with_openssl="no"
-
-fi;
-
     if test "$with_cwinux" = "no"; then
         { { echo "$as_me:$LINENO: error: You need to specify the cwinux directory using --with-cwinux" >&5
 echo "$as_me: error: You need to specify the cwinux directory using --with-cwinux" >&2;}
    { (exit 1); exit 1; }; }
     else
         # make sure that a well known include file exists
-        if test -e $with_cwinux/include/app/CwxAppFramework.h; then
+        if test -e $with_cwinux/app/CwxAppFramework.h; then
             cwinux_dir=$with_cwinux
             echo "$as_me:$LINENO: result: cwinux found!" >&5
 echo "${ECHO_T}cwinux found!" >&6
@@ -18953,40 +18939,22 @@ echo "$as_me: error: $with_cwinux not found.  Check the value you specified with
         fi
     fi
 
-    if test "$with_zk" = "no"; then
-        { { echo "$as_me:$LINENO: error: You need to specify the zookeeper directory using --with-zk" >&5
-echo "$as_me: error: You need to specify the zookeeper directory using --with-zk" >&2;}
+    if test "$with_protobuf" = "no"; then
+        { { echo "$as_me:$LINENO: error: You need to specify the protobuf directory using --with-protobuf" >&5
+echo "$as_me: error: You need to specify the protobuf directory using --with-protobuf" >&2;}
    { (exit 1); exit 1; }; }
     else
         # make sure that a well known include file exists
-        if test -e $with_zk/include/zookeeper.h; then
-            zk_dir=$with_zk
-            echo "$as_me:$LINENO: result: zookeeper found!" >&5
-echo "${ECHO_T}zookeeper found!" >&6
+        if test -e $with_protobuf/message.h; then
+            protobuf_dir=$with_protobuf
+            echo "$as_me:$LINENO: result: protobuf found!" >&5
+echo "${ECHO_T}protobuf found!" >&6
         else
-            { { echo "$as_me:$LINENO: error: $with_zk not found.  Check the value you specified with --with-zk" >&5
-echo "$as_me: error: $with_zk not found.  Check the value you specified with --with-zk" >&2;}
+            { { echo "$as_me:$LINENO: error: $with_protobuf not found.  Check the value you specified with --with-protobuf" >&5
+echo "$as_me: error: $with_protobuf not found.  Check the value you specified with --with-protobuf" >&2;}
    { (exit 1); exit 1; }; }
         fi
     fi
-
-    if test "$with_openssl" = "no"; then
-        { { echo "$as_me:$LINENO: error: You need to specify the openssl directory using --with-openssl" >&5
-echo "$as_me: error: You need to specify the openssl directory using --with-openssl" >&2;}
-   { (exit 1); exit 1; }; }
-    else
-        # make sure that a well known include file exists
-        if test -e $with_openssl/include/openssl/ssl.h; then
-            openssl_dir=$with_openssl
-            echo "$as_me:$LINENO: result: openssl found!" >&5
-echo "${ECHO_T}openssl found!" >&6
-        else
-            { { echo "$as_me:$LINENO: error: $with_openssl not found.  Check the value you specified with --with-openssl" >&5
-echo "$as_me: error: $with_openssl not found.  Check the value you specified with --with-openssl" >&2;}
-   { (exit 1); exit 1; }; }
-        fi
-    fi
-
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -19012,6 +18980,7 @@ _ACEOF
 
 
 # The AC_SUBST macro causes the variable to be saved in config.status
+
 
 
 
@@ -19752,6 +19721,7 @@ s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@cwinux_dir@,$cwinux_dir,;t t
+s,@protobuf_dir@,$protobuf_dir,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
